/**
 *
 * LBLMC Vivado HLS Simulation Engine for FPGA Designs
 *
 * Auto-generated by SimulationEngineGenerator Object
 *
 */

#ifndef RLC_Circuit_SIMULATIONENGINE_HPP
#define RLC_Circuit_SIMULATIONENGINE_HPP

template <int instance, typename real>
void RLC_Circuit_solver(real x_out[2], real *l_current_ind) {
  // MODEL PARAMETERS

  const static real VOLTAGE_Vs = 1.0000000000000000e+02;
  const static real RES_Vs = 1.0000000000000000e-03;
  const static real SRC_CURRENT_Vs = 1.0000000000000000e+05;

  const static real DT_ind = 4.9999999999999998e-08;
  const static real IND_ind = 1.0000000000000000e-03;
  const static real HOL2_ind = 2.4999999999999998e-05;

  const static real DT_cap = 4.9999999999999998e-08;
  const static real CAP_cap = 1.0000000000000000e-03;
  const static real HOC2_cap = 4.0000000000000000e+04;

  // COMPONENT FIELDS AND STATES

  static real epos_past_ind = 0.0000000000000000e+00;
  static real eneg_past_ind = 0.0000000000000000e+00;
  static real delta_v_ind = 0.0000000000000000e+00;
  static real current_ind = 0.0000000000000000e+00;
  static real current_eq_ind = 0.0000000000000000e+00;
  static real current_eq_past_ind = 0.0000000000000000e+00;

  static real epos_past_cap = 0.0000000000000000e+00;
  static real eneg_past_cap = 0.0000000000000000e+00;
  static real delta_v_cap = 0.0000000000000000e+00;
  static real current_cap = 0.0000000000000000e+00;
  static real current_eq_cap = 0.0000000000000000e+00;
  static real current_eq_past_cap = 0.0000000000000000e+00;

  // MODEL SOLUTIONS

  static real b[2];
  static real x[3];
  real b_components[3];

  // INVERTED CONDUCTANCE MATRIX

  const static real inv_g[2][2] = {
      {9.9999997500000055e-04, 6.2499842148832261e-13},
      {6.2499842148832261e-13, 2.4999937484531329e-05}};

  // COMPONENT SOURCE CONTRIBUTION UPDATES

  b_components[0] = SRC_CURRENT_Vs;

  epos_past_ind = x[1];
  eneg_past_ind = x[2];
  current_eq_past_ind = current_eq_ind;
  delta_v_ind = epos_past_ind - eneg_past_ind;
  current_ind = HOL2_ind * delta_v_ind - current_eq_past_ind;
  current_eq_ind = -current_ind - HOL2_ind * delta_v_ind;
  b_components[1] = current_eq_ind;

  epos_past_cap = x[2];
  eneg_past_cap = x[0];
  current_eq_past_cap = current_eq_cap;
  delta_v_cap = epos_past_cap - eneg_past_cap;
  current_cap = HOC2_cap * delta_v_cap - current_eq_past_cap;
  current_eq_cap = current_cap + HOC2_cap * delta_v_cap;
  b_components[2] = current_eq_cap;

  // MODEL OUTPUT SIGNAL UPDATES

  *l_current_ind = current_ind;

  // AGGREGRATE COMPONENT SOURCE CONTRIBUTIONS

  b[0] = b_components[0] + b_components[1];
  b[1] = -b_components[1] + b_components[2];

  // MODEL UPDATE SOLUTIONS

  x[0] = 0.0;
  x[1] = inv_g[0][0] * b[0];
  x[2] = real(0.0) + inv_g[1][1] * b[1];

  x_out[0] = x[1];
  x_out[1] = x[2];
}

#endif